/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : shell-execute
 #	author : miyako
 #	2015/08/21
 #
 # --------------------------------------------------------------------------------*/

#if VERSIONWIN
#include <tlhelp32.h>
#endif

// --- shell-execute
void Find_best_application(sLONG_PTR *pResult, PackagePtr pParams);
void GET_PROCESS_LIST(sLONG_PTR *pResult, PackagePtr pParams);
void OPEN_WITH_APPLICATION(sLONG_PTR *pResult, PackagePtr pParams);
void PRINT_WITH_APPLICATION(sLONG_PTR *pResult, PackagePtr pParams);
